version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: senha@123
      MYSQL_DATABASE: fornecedoresdb
    ports:
      - "3306:3306"

  api:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: >
      sh -c "node script_db.js && npm start"
